### ISSUE TITLE
Save *Clients

### ISSUE THREAD

**Issue by philhofer** [lafikl/fluent#1]
`*http.Client` objects are designed to be re-used, as they maintain a pool of TCP connections and all sorts of other goodies; allocating a new one on every request introduces all sorts of unnecessary overhead.

You should probably just use `http.DefaultClient` as your client for requests, as it is thread-safe and provides sane defaults. Alternatively, you could have the user provide an `http.Client` to wrap.

**Comment by lafikl** [comment]
The problem with using the DefaultClient is that you can't set a timeout for the request.

I think the best approach is using the DefaultClient if you didn't specify a timeout. But if you call `req.Timeout` then i create a client for you.

What do you think?

**Comment by philhofer** [comment]
That would work. Alternatively, options that are properties of the client could just be set by `(*Request).Use(c *http.Client)`

**Comment by lafikl** [comment]
I have other plans form `Use` for middleware ;)
How about `(*Request).Client(c *http.Client)`?
