### ISSUE TITLE
Import path

### ISSUE THREAD

**Issue by icholy** [lafikl/fluent#3]
``` go
package main

import "github.com/lafikl/go-fluent"

func main() {
    _ = fluent.New() // I had to check your source to know the package name
}
```

Not everyone does this, but the convention is to have the final segment of the import path to match the package name.

`github.com/lafikl/go-fluent` -> `github.com/lafikl/fluent`

**Comment by lafikl** [comment]
I don't think it's an idiom or a convention either (?)

**Comment by icholy** [comment]
https://golang.org/doc/code.html#PackageNames

> Go's convention is that the package name is the last element of the import path: the package imported as "crypto/rot13" should be named rot13.

fyi, github will automatically redirect ~~when~~ if you change the name

**Comment by lafikl** [comment]
Done, thanks.
